/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  owner: string;
  token: string;
}
export type ExecuteMsg = {
  update_owner: {
    owner: string;
  };
} | {
  update_config: {
    config: UpdateConfigMsg;
  };
} | {
  receive: Cw20ReceiveMsg;
} | {
  claim: {};
} | {
  unstake: {
    amount: Uint128;
  };
};
export type Uint128 = string;
export type Binary = string;
export interface UpdateConfigMsg {
  reward_contract?: string | null;
  token?: string | null;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export type QueryMsg = {
  config: {};
} | {
  owner: {};
} | {
  total_staking: {};
} | {
  staking: {
    user: string;
  };
} | {
  reward: {
    user: string;
  };
};
export type Addr = string;
export interface Config {
  reward_contract: Addr;
  token: Addr;
}
export interface UserRewardResponse {
  eclip: Uint128;
  eclipastro: Uint128;
}