[package]
name = "astroport-incentives"
version = "1.2.0-vxastro-rc.1"
authors = ["Astroport"]
edition = "2021"
description = "Astroport Incentives Contract distributing rewards to LP stakers"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport"
homepage = "https://astroport.fi"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-std.workspace = true
cw-storage-plus.workspace = true
cosmwasm-schema.workspace = true
cw2.workspace = true
cw20.workspace = true
cw-utils.workspace = true
astroport.workspace = true
thiserror.workspace = true
itertools.workspace = true
