[workspace]
members = [
    "contracts/*",
    "packages/*",
    "multitests",
]
# exclude = [
#     "packages/astroport-voting-escrow-mock",
#     "packages/astroport-escrow-fee-distributor-mock",
# ]
resolver = "2"

[workspace.package]
version    = "0.1.1"
edition    = "2021"
repository = "https://github.com/EclipsePad/equinox-contracts"
authors    = ["Tadao Fukuda"]
license    = "Apache-2.0"

[workspace.dependencies]
anyhow                  = "1"
cosmwasm-schema         = "1.1.0"
cosmwasm-std            = "1.1"
cw2                     = "1.1.0"
cw20                    = "1.1.0"
cw20-base               = { version = "1.1.0", features = ["library"] }
cw-controllers          = "1.0.1"
cw-multi-test           = "0.16"
cw-storage-plus         = "1.0.1"
cw-utils                = "1.0.1"
schemars                = "0.8.1"
semver                  = "1.0.20"
serde                   = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror               = "1.0.23"

equinox-msg             = { path = "./packages/equinox_msg" }
eclipse-base            = { path = "./packages/eclipse-base" }
minter-mocks            = { path = "./packages/minter-mocks" }
cw20-gift               = { path = "./packages/cw20-gift" }
eclipastro-token        = { path = "./contracts/token" }
token-converter         = { path = "./contracts/token_converter" }
flexible-staking        = { path = "./contracts/flexible_staking" }
timelock-staking        = { path = "./contracts/timelock_staking" }
reward-distributor      = { path = "./contracts/reward_distributor" }
voter                   = { path = "./contracts/voter" }
lp-staking              = { path = "./contracts/lp_staking" }
lockdrop                = { path = "./contracts/lockdrop" }
# gauge-contract          = { path = "./contracts/gauge_contract", features = ["library"] }
astroport-factory       = { git = "https://github.com/astroport-fi/astroport-core.git", version = "1.7.0" }
astroport-incentives    = { git = "https://github.com/astroport-fi/astroport-core.git", version = "1.0.1" }
astroport-pair          = { git = "https://github.com/astroport-fi/astroport-core.git", version = "1.5.0" }
astroport-pair-stable   = { git = "https://github.com/astroport-fi/astroport-core.git", version = "3.4.0" }
astroport-router        = { git = "https://github.com/astroport-fi/astroport-core.git", version = "1.2.0" }
astroport-token         = { git = "https://github.com/astroport-fi/astroport-core.git", version = "1.1.1" }
astroport-staking       = { git = "https://github.com/astroport-fi/astroport-core.git", version = "1.1.0" }
astroport-vesting       = { git = "https://github.com/astroport-fi/astroport-core.git", version = "1.3.2" }
astroport-xastro-token  = { git = "https://github.com/astroport-fi/astroport-core.git", version = "1.1.0" }
astroport               = { git = "https://github.com/astroport-fi/astroport-core.git", version = "3.10.0" }

astroport-generator     = { git = "https://github.com/astroport-fi/astroport-core.git" }
astroport-whitelist     = { git = "https://github.com/astroport-fi/astroport-core.git" }
# astroport-pair-stable   = { git = "https://github.com/astroport-fi/astroport-core.git", version = "3.4.0" }
astroport-governance    = { git = "https://github.com/astroport-fi/astroport-governance.git" }

# updated astroport contracts for integration testing
astroport-voting-escrow = { path = "./packages/astroport_voting_escrow" }
astroport-generator-controller = { path = "./packages/astroport_generator_controller" }
# astroport-escrow-fee-distributor = { path = "./packages/astroport_escrow_fee_distributor" }

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
