/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  astro: Addr;
  astro_staking: Addr;
  xastro: Addr;
}
export type ExecuteMsg = {
  claim: {};
};
export type QueryMsg = {
  last_claimed: {
    addr: string;
  };
};
export interface MigrateMsg {}
export interface LastClaimedResponse {
  last_claim_at: number;
}