/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from ".types";
import * as _1 from ".client";
import * as _2 from ".message-composer";
import * as _3 from ".react-query";
import * as _4 from ".recoil";
export namespace contracts {
  export const = { ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4
  };
}