/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Logo = {
  url: string;
} | {
  embedded: EmbeddedLogo;
};
export type EmbeddedLogo = {
  svg: Binary;
} | {
  png: Binary;
};
export type Binary = string;
export interface InstantiateMsg {
  marketing?: InstantiateMarketingInfo | null;
  owner: string;
  token_code_id: number;
  token_in: string;
  treasury: string;
  xtoken: string;
}
export interface InstantiateMarketingInfo {
  description?: string | null;
  logo?: Logo | null;
  marketing?: string | null;
  project?: string | null;
}
export type ExecuteMsg = {
  receive: Cw20ReceiveMsg;
} | {
  update_config: {
    config: UpdateConfig;
  };
} | {
  update_reward_config: {
    config: RewardConfig;
  };
} | {
  update_owner: {
    owner: string;
  };
} | {
  claim: {};
} | {
  claim_treasury_reward: {
    amount: Uint128;
  };
} | {
  withdraw_available_balance: {
    amount: Uint128;
    recipient: string;
  };
};
export type Uint128 = string;
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
}
export interface UpdateConfig {
  ce_reward_distributor?: string | null;
  stability_pool?: string | null;
  staking_reward_distributor?: string | null;
  token_in?: string | null;
  token_out?: string | null;
  treasury?: string | null;
  vxtoken_holder?: string | null;
  xtoken?: string | null;
}
export interface RewardConfig {
  ce_holders: number;
  stability_pool: number;
  treasury: number;
  users: number;
}
export type QueryMsg = {
  config: {};
} | {
  reward_config: {};
} | {
  rewards: {};
} | {
  owner: {};
} | {
  withdrawable_balance: {};
};
export type Addr = string;
export interface Config {
  ce_reward_distributor: Addr;
  stability_pool: Addr;
  staking_reward_distributor: Addr;
  token_in: Addr;
  token_out: Addr;
  treasury: Addr;
  vxtoken_holder: Addr;
  xtoken: Addr;
}
export interface RewardResponse {
  ce_holders_reward: Reward;
  stability_pool_reward: Reward;
  treasury_reward: Reward;
  users_reward: Reward;
}
export interface Reward {
  amount: Uint128;
  token: string;
}