/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.9.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { AssetInfo, Addr, InstantiateMsg, ExecuteMsg, CallbackMsg, Uint128, UpdateConfigMsg, RewardDistribution, Asset, QueryMsg, ArrayOfString, ArrayOfRewardAmount, RewardAmount, Config, Boolean, Reward, ArrayOfTupleOfTupleOfUint64Anduint64AndReward, Decimal256, ArrayOfRewardWeight, RewardWeight, UserStaking, ArrayOfUnbondedItem, UnbondedItem } from "./LpStaking.types";
export interface LpStakingReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<Config>;
  rewardDistribution: () => Promise<Reward>;
  owner: () => Promise<Addr>;
  totalStaking: () => Promise<Uint128>;
  staking: ({
    user
  }: {
    user: string;
  }) => Promise<UserStaking>;
  unbonded: ({
    user
  }: {
    user: string;
  }) => Promise<ArrayOfUnbondedItem>;
  reward: ({
    user
  }: {
    user: string;
  }) => Promise<ArrayOfRewardAmount>;
  rewardWeights: () => Promise<ArrayOfRewardWeight>;
  userRewardWeights: ({
    user
  }: {
    user: string;
  }) => Promise<ArrayOfRewardWeight>;
  blacklist: () => Promise<ArrayOfString>;
  isAllowed: ({
    user
  }: {
    user: string;
  }) => Promise<Boolean>;
  rewardSchedule: ({
    from
  }: {
    from?: number;
  }) => Promise<ArrayOfTupleOfTupleOfUint64AndUint64AndReward>;
}
export class LpStakingQueryClient implements LpStakingReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.rewardDistribution = this.rewardDistribution.bind(this);
    this.owner = this.owner.bind(this);
    this.totalStaking = this.totalStaking.bind(this);
    this.staking = this.staking.bind(this);
    this.unbonded = this.unbonded.bind(this);
    this.reward = this.reward.bind(this);
    this.rewardWeights = this.rewardWeights.bind(this);
    this.userRewardWeights = this.userRewardWeights.bind(this);
    this.blacklist = this.blacklist.bind(this);
    this.isAllowed = this.isAllowed.bind(this);
    this.rewardSchedule = this.rewardSchedule.bind(this);
  }
  config = async (): Promise<Config> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  rewardDistribution = async (): Promise<Reward> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reward_distribution: {}
    });
  };
  owner = async (): Promise<Addr> => {
    return this.client.queryContractSmart(this.contractAddress, {
      owner: {}
    });
  };
  totalStaking = async (): Promise<Uint128> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_staking: {}
    });
  };
  staking = async ({
    user
  }: {
    user: string;
  }): Promise<UserStaking> => {
    return this.client.queryContractSmart(this.contractAddress, {
      staking: {
        user
      }
    });
  };
  unbonded = async ({
    user
  }: {
    user: string;
  }): Promise<ArrayOfUnbondedItem> => {
    return this.client.queryContractSmart(this.contractAddress, {
      unbonded: {
        user
      }
    });
  };
  reward = async ({
    user
  }: {
    user: string;
  }): Promise<ArrayOfRewardAmount> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reward: {
        user
      }
    });
  };
  rewardWeights = async (): Promise<ArrayOfRewardWeight> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reward_weights: {}
    });
  };
  userRewardWeights = async ({
    user
  }: {
    user: string;
  }): Promise<ArrayOfRewardWeight> => {
    return this.client.queryContractSmart(this.contractAddress, {
      user_reward_weights: {
        user
      }
    });
  };
  blacklist = async (): Promise<ArrayOfString> => {
    return this.client.queryContractSmart(this.contractAddress, {
      blacklist: {}
    });
  };
  isAllowed = async ({
    user
  }: {
    user: string;
  }): Promise<Boolean> => {
    return this.client.queryContractSmart(this.contractAddress, {
      is_allowed: {
        user
      }
    });
  };
  rewardSchedule = async ({
    from
  }: {
    from?: number;
  }): Promise<ArrayOfTupleOfTupleOfUint64AndUint64AndReward> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reward_schedule: {
        from
      }
    });
  };
}
export interface LpStakingInterface extends LpStakingReadOnlyInterface {
  contractAddress: string;
  sender: string;
  proposeNewOwner: ({
    expiresIn,
    owner
  }: {
    expiresIn: number;
    owner: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  dropOwnershipProposal: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claimOwnership: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    config
  }: {
    config: UpdateConfigMsg;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateRewardDistribution: ({
    distribution
  }: {
    distribution: RewardDistribution;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claim: ({
    assets
  }: {
    assets?: AssetInfo[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  callback: (callbackMsg: CallbackMsg, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unstake: ({
    amount,
    recipient
  }: {
    amount: Uint128;
    recipient?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  stake: ({
    recipient
  }: {
    recipient?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  unbond: ({
    amount,
    period
  }: {
    amount?: Uint128;
    period: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdraw: ({
    recipient
  }: {
    recipient?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  addRewards: ({
    beclip,
    duration,
    eclip,
    from
  }: {
    beclip: Uint128;
    duration?: number;
    eclip: Uint128;
    from?: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claimBlacklistRewards: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  allowUsers: ({
    users
  }: {
    users: string[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  blockUsers: ({
    users
  }: {
    users: string[];
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  removeFromBlacklist: ({
    user
  }: {
    user: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class LpStakingClient extends LpStakingQueryClient implements LpStakingInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;
  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.proposeNewOwner = this.proposeNewOwner.bind(this);
    this.dropOwnershipProposal = this.dropOwnershipProposal.bind(this);
    this.claimOwnership = this.claimOwnership.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.updateRewardDistribution = this.updateRewardDistribution.bind(this);
    this.claim = this.claim.bind(this);
    this.callback = this.callback.bind(this);
    this.unstake = this.unstake.bind(this);
    this.stake = this.stake.bind(this);
    this.unbond = this.unbond.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.addRewards = this.addRewards.bind(this);
    this.claimBlacklistRewards = this.claimBlacklistRewards.bind(this);
    this.allowUsers = this.allowUsers.bind(this);
    this.blockUsers = this.blockUsers.bind(this);
    this.removeFromBlacklist = this.removeFromBlacklist.bind(this);
  }
  proposeNewOwner = async ({
    expiresIn,
    owner
  }: {
    expiresIn: number;
    owner: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      propose_new_owner: {
        expires_in: expiresIn,
        owner
      }
    }, fee, memo, _funds);
  };
  dropOwnershipProposal = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      drop_ownership_proposal: {}
    }, fee, memo, _funds);
  };
  claimOwnership = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_ownership: {}
    }, fee, memo, _funds);
  };
  updateConfig = async ({
    config
  }: {
    config: UpdateConfigMsg;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        config
      }
    }, fee, memo, _funds);
  };
  updateRewardDistribution = async ({
    distribution
  }: {
    distribution: RewardDistribution;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_reward_distribution: {
        distribution
      }
    }, fee, memo, _funds);
  };
  claim = async ({
    assets
  }: {
    assets?: AssetInfo[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim: {
        assets
      }
    }, fee, memo, _funds);
  };
  callback = async (callbackMsg: CallbackMsg, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      callback: callbackMsg
    }, fee, memo, _funds);
  };
  unstake = async ({
    amount,
    recipient
  }: {
    amount: Uint128;
    recipient?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unstake: {
        amount,
        recipient
      }
    }, fee, memo, _funds);
  };
  stake = async ({
    recipient
  }: {
    recipient?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      stake: {
        recipient
      }
    }, fee, memo, _funds);
  };
  unbond = async ({
    amount,
    period
  }: {
    amount?: Uint128;
    period: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      unbond: {
        amount,
        period
      }
    }, fee, memo, _funds);
  };
  withdraw = async ({
    recipient
  }: {
    recipient?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        recipient
      }
    }, fee, memo, _funds);
  };
  addRewards = async ({
    beclip,
    duration,
    eclip,
    from
  }: {
    beclip: Uint128;
    duration?: number;
    eclip: Uint128;
    from?: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      add_rewards: {
        beclip,
        duration,
        eclip,
        from
      }
    }, fee, memo, _funds);
  };
  claimBlacklistRewards = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_blacklist_rewards: {}
    }, fee, memo, _funds);
  };
  allowUsers = async ({
    users
  }: {
    users: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      allow_users: {
        users
      }
    }, fee, memo, _funds);
  };
  blockUsers = async ({
    users
  }: {
    users: string[];
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      block_users: {
        users
      }
    }, fee, memo, _funds);
  };
  removeFromBlacklist = async ({
    user
  }: {
    user: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      remove_from_blacklist: {
        user
      }
    }, fee, memo, _funds);
  };
}