[package]
name = "astroport-tokenfactory-tracker"
version = "1.0.0"
edition = "2021"

[features]
library = []
tests-tube = ["test-tube", "neutron-test-tube"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cw2.workspace = true
cosmwasm-std = { workspace = true, features = ["cosmwasm_1_1"] }
cw-storage-plus.workspace = true
cosmwasm-schema.workspace = true
thiserror.workspace = true
astroport = "4"

#Optional dependencies
neutron-test-tube = { git = "https://github.com/j0nl1/neutron-test-tube", optional = true }
test-tube = { git = "https://github.com/j0nl1/neutron-test-tube", optional = true }
