/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {}
export type ExecuteMsg = {
  claim: {};
};
export type QueryMsg = {
  denom: {};
} | {
  last_claimed: {
    addr: string;
  };
};
export interface MigrateMsg {
  version: string;
}
export type String = string;
export interface LastClaimedResponse {
  last_claim_at: number;
}